package app.pwhs.blockads.service

import android.content.Context
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject
import timber.log.Timber
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Downloads and re-validates the remote skip-rule table from
 * liangrk/blockads-skip-rules (same CDN mirror chain as the DNS filters).
 *
 * Defense in depth: the dist is generated by a whitelist converter, but
 * the client re-validates every pattern against the same word lists
 * before use - even a compromised dist cannot make the service tap
 * arbitrary UI. Download failures are silent: the built-in global
 * matcher covers the general case.
 */
object SkipRuleLoader {

    private val MIRRORS = listOf(
        "https://cdn.jsdelivr.net/gh/liangrk/blockads-skip-rules@main/dist",
        "https://fastly.jsdelivr.net/gh/liangrk/blockads-skip-rules@main/dist",
        "https://gcore.jsdelivr.net/gh/liangrk/blockads-skip-rules@main/dist",
        "https://ghfast.top/https://raw.githubusercontent.com/liangrk/blockads-skip-rules/main/dist",
        "https://ghp.ci/https://raw.githubusercontent.com/liangrk/blockads-skip-rules/main/dist"
    )

    // Word lists must stay in sync with SkipRuleMatcher and the converter.
    private val SAFE_TEXT_TERMS = listOf("跳过", "跳過", "skip")
    private val SAFE_VID_HINTS = listOf("skip", "count", "down", "close", "jump")
    private val SAFE_ID_SUFFIXES = listOf("tt_splash_skip_btn")

    private const val MAX_APPS = 1000
    private const val MAX_PATTERNS = 20
    private const val MAX_PATTERN_LEN = 60

    /** pkg -> AppRules after local re-validation. */
    @Volatile
    var rules: ConcurrentHashMap<String, AppRules> = ConcurrentHashMap()
        private set

    private val loading = AtomicBoolean(false)

    class AppRules(
        val texts: List<String>,
        val vids: List<String>,
        val idSuffixes: List<String>,
        val activityIds: Set<String>
    )

    /** Fire-and-forget download + re-validation. Idempotent. */
    fun loadAsync(context: Context) {
        if (!loading.compareAndSet(false, true)) return
        CoroutineScope(Dispatchers.IO).launch {
            try {
                val dir = context.filesDir
                val cached = java.io.File(dir, "skip_rules.json")
                val verFile = java.io.File(dir, "skip_rules.version")
                val stored = if (verFile.exists())
                    verFile.readText().trim().toLongOrNull() ?: 0L else 0L

                var remoteVer = 0L
                var base: String? = null
                for (m in MIRRORS) {
                    val v = probe(m)
                    if (v != null) {
                        remoteVer = v
                        base = m
                        if (remoteVer > stored) break
                    }
                }
                if (base == null || remoteVer <= stored) {
                    if (cached.exists() && rules.isEmpty()) parse(cached.readText())
                    return@launch
                }
                val body = download("$base/skip-rules.json") ?: return@launch
                if (parse(body)) {
                    cached.writeText(body)
                    verFile.writeText(remoteVer.toString())
                    Timber.i("SkipRules loaded %d apps (v%d)", rules.size, remoteVer)
                }
            } catch (e: Exception) {
                Timber.d("SkipRules load failed: %s", e.message)
            } finally {
                loading.set(false)
            }
        }
    }
    /** Returns the remote version from the first reachable mirror. */
    private fun probe(mirror: String): Long? = try {
        val c = connect(mirror + "/skip-rules.version", 8000)
        c.inputStream.bufferedReader().readText().trim().toLongOrNull()
    } catch (_: Exception) {
        null
    }

    private fun download(url: String): String? = try {
        val c = connect(url, 20000)
        c.inputStream.bufferedReader().readText()
    } catch (_: Exception) {
        null
    }

    private fun connect(url: String, timeoutMs: Int): HttpURLConnection {
        val c = URL(url).openConnection() as HttpURLConnection
        c.connectTimeout = timeoutMs
        c.readTimeout = timeoutMs
        c.instanceFollowRedirects = true
        return c
    }

    /** Parse + local re-validation. Returns true when safe to use. */
    private fun parse(body: String): Boolean = try {
        val obj = JSONObject(body)
        val out = ConcurrentHashMap<String, AppRules>()
        val apps = obj.getJSONArray("apps")
        for (i in 0 until minOf(apps.length(), MAX_APPS)) {
            val a = apps.optJSONObject(i) ?: continue
            val pkg = a.optString("pkg", "")
            if (!pkg.matches(Regex("[a-zA-Z0-9_.]{3,120}"))) continue
            val texts = okPatterns(a, "texts", SAFE_TEXT_TERMS)
            val vids = okPatterns(a, "vids", SAFE_VID_HINTS)
            val sfx = mutableListOf<String>()
            val sa = a.optJSONArray("idSuffixes") ?: JSONArray()
            for (j in 0 until minOf(sa.length(), MAX_PATTERNS)) {
                val p = sa.optString(j, "")
                if (p.length <= MAX_PATTERN_LEN &&
                    SAFE_ID_SUFFIXES.any { p.endsWith(it) }
                ) sfx.add(p)
            }
            val acts = mutableSetOf<String>()
            val aa = a.optJSONArray("activityIds") ?: JSONArray()
            for (j in 0 until minOf(aa.length(), 10)) {
                val p = aa.optString(j, "")
                if (p.matches(Regex("[a-zA-Z0-9_.$]{3,200}"))) acts.add(p)
            }
            if (texts.isEmpty() && vids.isEmpty() && sfx.isEmpty()) continue
            out[pkg] = AppRules(texts, vids, sfx, acts)
        }
        rules = out
        true
    } catch (e: Exception) {
        Timber.d("SkipRules parse failed: %s", e.message)
        false
    }

    /** Keep only patterns matching the safety word list (fail-closed). */
    private fun okPatterns(a: JSONObject, name: String, words: List<String>): List<String> {
        val arr = a.optJSONArray(name) ?: return emptyList()
        val out = mutableListOf<String>()
        for (j in 0 until minOf(arr.length(), MAX_PATTERNS)) {
            val p = arr.optString(j, "")
            if (p.isNotEmpty() && p.length <= MAX_PATTERN_LEN &&
                words.any { p.contains(it, ignoreCase = true) }
            ) out.add(p)
        }
        return out
    }
}
